### ISSUE TITLE
Crash when trying to unfavorite topic

### ISSUE THREAD

**Issue by JakeThurman** [jack-and-the-beans/buddies-ios#50] opened 2019-02-21 00:20 UTC
```
2019-02-20 19:18:20.065105-0500 Buddies[75804:3239111] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete row 1 from section 0 which only contains 1 rows before the update'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112e251bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001123c3735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112e24f42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010f2dd877 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   UIKitCore                           0x00000001189ca77f -[UITableView _endCellAnimationsWithContext:] + 4992
	5   UIKitCore                           0x00000001189e8cb0 -[UITableView _updateRowsAtIndexPaths:withUpdateAction:rowAnimation:usingPresentationValues:] + 1384
	6   UIKitCore                           0x00000001189e9041 -[UITableView reloadRowsAtIndexPaths:withRowAnimation:] + 133
	7   Buddies                             0x000000010d120445 $S7Buddies15ActivityTableVCC8loadData3for12dataAccessor14storageManagerySaySaySSGG_AA0fI0CAA07StorageK0CtFyycfU0_ + 437
	8   Buddies                             0x000000010d1204d9 $S7Buddies15ActivityTableVCC8loadData3for12dataAccessor14storageManagerySaySaySSGG_AA0fI0CAA07StorageK0CtFyycfU0_TA + 25
	9   Buddies                             0x000000010d11d54b $S7Buddies15ActivityTableVCC8loadUser3uid12dataAccessor14storageManager8onLoadedySS_AA04DataI0CAA07StorageK0CyycSgtFyAA0F0CcfU_ + 587
	10  Buddies                             0x000000010d11d5f9 $S7Buddies15ActivityTableVCC8loadUser3uid12dataAccessor14storageManager8onLoadedySS_AA04DataI0CAA07StorageK0CyycSgtFyAA0F0CcfU_TA + 25
	11  Buddies                             0x000000010d12914f $S7Buddies4UserCIegg_ACIegn_TR + 15
	12  Buddies                             0x000000010d1291b1 $S7Buddies4UserCIegg_ACIegn_TRTA + 17
	13  Buddies                             0x000000010d12d683 $S7Buddies12DataAccessorC16onInvalidateUser4useryAA0F0C_tFyAA8ListenerCyAGGXEfU_ + 115
	14  Buddies                             0x000000010d12d6ac $S7Buddies12DataAccessorC16onInvalidateUser4useryAA0F0C_tFyAA8ListenerCyAGGXEfU_TA + 12
	15  Buddies                             0x000000010d12d6c9 $S7Buddies8ListenerCyAA4UserCGs5Error_pIggzo_AFsAG_pIegnzo_TR + 25
	16  Buddies                             0x000000010d12d74b $S7Buddies8ListenerCyAA4UserCGs5Error_pIggzo_AFsAG_pIegnzo_TRTA + 27
	17  libswiftCore.dylib                  0x000000011454e560 $SSTsE7forEachyyy7ElementQzKXEKF + 352
	18  Buddies                             0x000000010d12d578 $S7Buddies12DataAccessorC16onInvalidateUser4useryAA0F0C_tF + 680
	19  Buddies                             0x000000010d12e228 $S7Buddies12DataAccessorCAA24UserInvalidationDelegateA2aDP012onInvalidateD04useryAA0D0C_tFTW + 24
	20  Buddies                             0x000000010d15f363 $S7Buddies4UserC8onChange33_1AA70359AEC9F07E8C54F5BF57259748LLyySS_ypSgtF + 227
	21  Buddies                             0x000000010d15dc48 $S7Buddies4UserC14favoriteTopicsSaySSGvW + 264
	22  Buddies                             0x000000010d15ddd3 $S7Buddies4UserC14favoriteTopicsSaySSGvs + 243
	23  Buddies                             0x000000010d0f62f2 $S7Buddies8TopicsVCC14toggleSelectedyyAA12ToggleButtonCF + 1794
	24  Buddies                             0x000000010d0f66dc $S7Buddies8TopicsVCC14toggleSelectedyyAA12ToggleButtonCFTo + 60
	25  UIKitCore                           0x00000001187c6ecb -[UIApplication sendAction:to:from:forEvent:] + 83
	26  UIKitCore                           0x00000001182020bd -[UIControl sendAction:to:forEvent:] + 67
	27  UIKitCore                           0x00000001182023da -[UIControl _sendActionsForEvents:withEvent:] + 450
	28  UIKitCore                           0x000000011820131e -[UIControl touchesEnded:withEvent:] + 583
	29  UIKitCore                           0x000000011839a018 _UIGestureEnvironmentSortAndSendDelayedTouches + 5387
	30  UIKitCore                           0x0000000118393fd1 _UIGestureEnvironmentUpdate + 1506
	31  UIKitCore                           0x00000001183939ad -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 478
	32  UIKitCore                           0x000000011839371d -[UIGestureEnvironment _updateForEvent:window:] + 200
	33  UIKitCore                           0x000000011880378a -[UIWindow sendEvent:] + 4058
	34  UIKitCore                           0x00000001187e1394 -[UIApplication sendEvent:] + 352
	35  UIKitCore                           0x00000001188b65a9 __dispatchPreprocessedEventFromEventQueue + 3054
	36  UIKitCore                           0x00000001188b91cb __handleEventQueueInternal + 5948
	37  CoreFoundation                      0x0000000112d8a721 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	38  CoreFoundation                      0x0000000112d89f93 __CFRunLoopDoSources0 + 243
	39  CoreFoundation                      0x0000000112d8463f __CFRunLoopRun + 1263
	40  CoreFoundation                      0x0000000112d83e11 CFRunLoopRunSpecific + 625
	41  GraphicsServices                    0x000000011c0fb1dd GSEventRunModal + 62
	42  UIKitCore                           0x00000001187c581d UIApplicationMain + 140
	43  Buddies                             0x000000010d0d6217 main + 71
	44  libdyld.dylib                       0x000000011527c575 start + 1
	45  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by lukemeierj** [comment] 2019-02-21 00:21
Any more info? Other topics favorited? Were you un/re-favoriting?  

Any steps to reproduce would be great

**Comment by JakeThurman** [comment] 2019-02-21 23:17
Received the same crash again, this time the app just sitting open on the "Movies" topic. I had giberish in the search bar such that there were no results.


```
2019-02-21 18:14:32.672928-0500 Buddies[99128:3684209] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete row 0 from section 0 which only contains 0 rows before the update'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011549e1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000114a3c735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011549df42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000111956877 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   UIKitCore                           0x000000011b48777f -[UITableView _endCellAnimationsWithContext:] + 4992
	5   UIKitCore                           0x000000011b4a5cb0 -[UITableView _updateRowsAtIndexPaths:withUpdateAction:rowAnimation:usingPresentationValues:] + 1384
	6   UIKitCore                           0x000000011b4a6041 -[UITableView reloadRowsAtIndexPaths:withRowAnimation:] + 133
	7   Buddies                             0x000000010f78fdd5 $S7Buddies15ActivityTableVCC8loadData3for12dataAccessor14storageManagerySaySaySSGG_AA0fI0CAA07StorageK0CtFyycfU0_ + 437
	8   Buddies                             0x000000010f78fe69 $S7Buddies15ActivityTableVCC8loadData3for12dataAccessor14storageManagerySaySaySSGG_AA0fI0CAA07StorageK0CtFyycfU0_TA + 25
	9   Buddies                             0x000000010f78cedb $S7Buddies15ActivityTableVCC8loadUser3uid12dataAccessor14storageManager8onLoadedySS_AA04DataI0CAA07StorageK0CyycSgtFyAA0F0CcfU_ + 587
	10  Buddies                             0x000000010f78cf89 $S7Buddies15ActivityTableVCC8loadUser3uid12dataAccessor14storageManager8onLoadedySS_AA04DataI0CAA07StorageK0CyycSgtFyAA0F0CcfU_TA + 25
	11  Buddies                             0x000000010f7989df $S7Buddies4UserCIegg_ACIegn_TR + 15
	12  Buddies                             0x000000010f798a41 $S7Buddies4UserCIegg_ACIegn_TRTA + 17
	13  Buddies                             0x000000010f79cf13 $S7Buddies12DataAccessorC16onInvalidateUser4useryAA0F0C_tFyAA8ListenerCyAGGXEfU_ + 115
	14  Buddies                             0x000000010f79cf3c $S7Buddies12DataAccessorC16onInvalidateUser4useryAA0F0C_tFyAA8ListenerCyAGGXEfU_TA + 12
	15  Buddies                             0x000000010f79cf59 $S7Buddies8ListenerCyAA4UserCGs5Error_pIggzo_AFsAG_pIegnzo_TR + 25
	16  Buddies                             0x000000010f79cfdb $S7Buddies8ListenerCyAA4UserCGs5Error_pIggzo_AFsAG_pIegnzo_TRTA + 27
	17  libswiftCore.dylib                  0x0000000116bc7560 $SSTsE7forEachyyy7ElementQzKXEKF + 352
	18  Buddies                             0x000000010f79ce08 $S7Buddies12DataAccessorC16onInvalidateUser4useryAA0F0C_tF + 680
	19  Buddies                             0x000000010f799ce7 $S7Buddies12DataAccessorC9_loadUser2idySS_tFySo19FIRDocumentSnapshotCSg_s5Error_pSgtcfU_ + 935
	20  Buddies                             0x000000010f79a1b5 $S7Buddies12DataAccessorC9_loadUser2idySS_tFySo19FIRDocumentSnapshotCSg_s5Error_pSgtcfU_TA + 21
	21  Buddies                             0x000000010f740784 $SSo19FIRDocumentSnapshotCSgs5Error_pSgIeggg_ACSo7NSErrorCSgIeyByy_TR + 132
	22  Buddies                             0x000000010f8fe28a __72-[FIRDocumentReference addSnapshotListenerInternalWithOptions:listener:]_block_invoke + 1178
	23  Buddies                             0x000000010f94fee9 _ZZZ45-[FSTAsyncQueryListener asyncSnapshotHandler]EUb_ENK3$_0clEv + 121
	24  Buddies                             0x000000010f94fe65 _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZZ45-[FSTAsyncQueryListener asyncSnapshotHandler]EUb_E3$_0EEEvDpOT_ + 117
	25  Buddies                             0x000000010f94faff _ZNSt3__110__function6__funcIZZ45-[FSTAsyncQueryListener asyncSnapshotHandler]EUb_E3$_0NS_9allocatorIS2_EEFvvEEclEv + 95
	26  Buddies                             0x000000010f9951ca _ZNKSt3__18functionIFvvEEclEv + 154
	27  Buddies                             0x000000010f8ccd23 _ZZN8firebase9firestore4util8internal13DispatchAsyncEPU28objcproto17OS_dispatch_queue8NSObjectONSt3__18functionIFvvEEEENK3$_0clEPv + 51
	28  Buddies                             0x000000010f8ccce8 _ZZN8firebase9firestore4util8internal13DispatchAsyncEPU28objcproto17OS_dispatch_queue8NSObjectONSt3__18functionIFvvEEEEN3$_08__invokeEPv + 24
	29  libdispatch.dylib                   0x000000011787f602 _dispatch_client_callout + 8
	30  libdispatch.dylib                   0x000000011788c99a _dispatch_main_queue_callback_4CF + 1541
	31  CoreFoundation                      0x00000001154033e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	32  CoreFoundation                      0x00000001153fda76 __CFRunLoopRun + 2342
	33  CoreFoundation                      0x00000001153fce11 CFRunLoopRunSpecific + 625
	34  GraphicsServices                    0x000000011a7a01dd GSEventRunModal + 62
	35  UIKitCore                           0x000000011b28281d UIApplicationMain + 140
	36  Buddies                             0x000000010f741137 main + 71
	37  libdyld.dylib                       0x00000001178f5575 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by JakeThurman** [comment] 2019-02-21 23:17
If we can even just log something where this crash occurs so we can get more data, that would be awesome.

**Comment by lukemeierj** [comment] 2019-02-22 06:39
I didn't look in much detail at first, but this isn't related to the Topics view.  Both of these are the activities table.

Are both or only the last from BUD-37?  The search component is not in master yet afaik.

It looks like for the second report (at least) the callbacks in the dataAccessor could be getting fired.  The initial indexPath of an activity is bound to the callback, and so when searching removes cells 1, 2, 3, and 4, there's no cell to update when the callback tries to update cell 6.

**Comment by lukemeierj** [comment] 2019-02-22 06:43
In the first stack trace, we can see that favoriting a topic triggered our eventual failure. 

Here's what probably happened:
1. You opened an `ActivityTableVC`
2. You went back to Topics.
3. You favorited a topic.
4. New favorited topic -> `invalidateUser`
5. Call the dataAccessor callback
6. Try to update the hidden tableview.  
    * Possible it has no cells, since it's hidden.

In the second one, it looks like the same story, but `invalidateListener` was called because of a change propagating from Firebase.

**Comment by lukemeierj** [comment] 2019-02-23 04:14
Fix merged.  Closing for now.

**Closed as completed by lukemeierj** 2019-02-23 04:14 UTC
